util.AddNetworkString("SendFirstKarma")

hook.Add("PlayerSpawn", "SendKarmaOnSpawn", function(player)
    timer.Simple(1, function()
        local karmaValue = Karma:ReturnKarma(player:SteamID64())
        net.Start("SendFirstKarma")
        net.WriteInt(karmaValue, 32)
        net.Send(player)
    end)
end)

hook.Add("PlayerInitialSpawn", "SendKarmaOnInitialSpawn", function(player)
    timer.Simple(1, function()
        local karmaValue = Karma:ReturnKarma(player:SteamID64())
        net.Start("SendFirstKarma")
        net.WriteInt(karmaValue, 32)
        net.Send(player)
    end)
end)
